### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sifte** [Kraots/disnake_docs#1]
- Replicate the command `docs` as a slash command with autocomplete.
- Add more libraries to the docs slash command maybe? (nextcord, etc)

`/docs library: disnake obj: disnake.Member`
`/docs library: python obj: os.listdir`

**Comment by Kraots** [comment]
Sure, will be implemented later today

**Comment by Kraots** [comment]
> * Replicate the command `docs` as a slash command with autocomplete.
> * Add more libraries to the docs slash command maybe? (nextcord, etc)
> 
> `/docs library: disnake obj: disnake.Member` `/docs library: python obj: os.listdir`

docs is now using slashes with autocomplete, however i won't do the second thing simply because that's for the user to decide, they can easily subclass and add their own libraries as shown [here](https://github.com/Kraots/disnake_docs#how-to-add-more-items).
With this i'm closing this issue.
